---
- hosts: all
  become: yes
  vars_files:
    -  vars/users.yaml
  roles:
    - role: base
    - role: ssummer3.osquery
    - role: ssummer3.sysdig

- hosts: election
  roles:
    - role: election
