---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    -  vars/users.yaml
  roles:
    - role: hackmichiana
    - role: ssummer3.sysdig

- hosts: election
  roles:
    - role: election
