---
- name: check for /etc/grub.conf
  stat:
    path: /etc/grub.conf
  register: grub

- name: tsc fix /etc/grub.conf
  lineinfile:
    name: /etc/grub.conf
    backrefs: true
    state: present
    regexp: '^(kernel .* selinux=0)$'
    line: '\1 clocksource=tsc'
  when: grub.stat.exists

- name: tsc fix /etc/rc.local
  lineinfile:
    name: /etc/rc.local
    line: 'echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource'

